# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: roadrunner120485's TechBlog
# email: roadrunner120485@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome on my tech blog. Here I will to publish articles about
  software and system architectures, tools and frameworks relating
  cloud and cluster computing.
baseurl: ""
url: "http://roadrunner120485.github.io/" # the base hostname & protocol for your site

twitter_username: roadrunner12048
github_username:  roadrunner120485

# Build settings
# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "footnotes"]
gems:
  - jemoji